export const SITE = {
  brand: "Ritelindo",
  brandFull: "Ritelindo Akselera Kolaborasi",
  tagline: "Pabrik Rak Minimarket & Paket Setup Toko Retail",
  waNumber: process.env.NEXT_PUBLIC_WA_NUMBER ?? "6281258576431",
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL ?? "https://landing-page-hantic.vercel.app",
  logoText: "Ritelindo",
  phone: "+62 812-5857-6431",
  email: "info@ritelindo.co.id",
  address: "Surabaya, Jawa Timur",
  serviceArea: "Jawa & Bali",
  freeShippingArea: "Jawa–Bali",
  freeInstallArea: "Jatim, Jateng & DIY",
  themeColor: "#1a6b3a",
} as const;
